using System.ComponentModel.Design;
using System.Security.Cryptography;
Console.WriteLine($"Hello, welcome to the newly improved and fully automated TripAdvisor! Give me some information about your planned       or desired trip and I'll help calculate costs!");
Console.WriteLine("Make sure to put only numerical values when asked for a number..."); 
Console.WriteLine("Where are you going?"); 
string Location = Console.ReadLine();
Console.WriteLine();
Console.WriteLine("Who's the driver?");
string Driver = Console.ReadLine();
Console.WriteLine();
Console.WriteLine($"How many miles to {Location}?");
string Distance = Console.ReadLine();
Console.WriteLine();
double DistanceNum = Convert.ToDouble(Distance);
Console.WriteLine($"What will be your average MPH {Driver}?");
string AvgMPH = Console.ReadLine();
Console.WriteLine();
double AvgMPHNum = Convert.ToDouble(AvgMPH);
Console.WriteLine($"How many Miles per Gallon does your vehicle average {Driver}?");
string AvgMPG = Console.ReadLine();
double AvgMPGNum = Convert.ToDouble(AvgMPG);
Console.WriteLine();
Console.WriteLine($"{Driver}, what size tank do you have in gallons?");
string tankSize = Console.ReadLine();
int tankSizeNum = Convert.ToInt32(tankSize);
Console.WriteLine();
Console.WriteLine($"How many passengers are going with you {Driver}?");
string PsgCount = Console.ReadLine();
int PsgCountNum = Convert.ToInt32(PsgCount);
Console.WriteLine();
Console.WriteLine($"{Driver}, what unit of currency do you use? Please only enter one of the following: $, £, or ¥"); //I'm getting an error for the €, so I excluded it
string Currency = Console.ReadLine();
Console.WriteLine();
Console.WriteLine($"What's the average price per gallon ({Currency}) en route to {Location}?");
string PPG =  Console.ReadLine();
double PPGNum = Convert.ToDouble(PPG);
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine($"Driver:{Driver, 50}");
Console.WriteLine($"Currency:{Currency,48}");
Console.WriteLine();
Console.WriteLine($"Distance in Miles:{DistanceNum,39}");
Console.WriteLine($"Average Velocity in MPH:{AvgMPHNum,33}");
double totaltime = DistanceNum / AvgMPHNum;
int hours = (int)totaltime;
int minutes = (int)((totaltime - hours) * 60 + 1);
Console.WriteLine($"Time Spent in travel: {hours,13} Hours, and {minutes} Minutes"); 
Console.WriteLine();
Console.WriteLine($"Miles Per Gallon: {AvgMPGNum,39}");
double fuelneeded = DistanceNum / AvgMPGNum;
Console.WriteLine($"Required Fuel: {fuelneeded,42:00.00}");
double stopsNeededdub = DistanceNum/(AvgMPGNum * tankSizeNum) + 1;
int stopsNeededint = Convert.ToInt32(stopsNeededdub);
double tankrange = AvgMPGNum * tankSizeNum;
Console.WriteLine($"Range per tank: {tankrange,41}");
Console.WriteLine($"Stops needed: {stopsNeededint,43}");
Console.WriteLine();
Console.WriteLine($"Fuel Price per Gallon ({Currency}): {PPGNum,30}");
double Fuelcost = fuelneeded * PPGNum;
Console.WriteLine($"Total Cost of fuel: {Fuelcost,37:00.00}");
Console.WriteLine($"Total Occupants: {PsgCountNum + 1,40}");
double CCP = Fuelcost / (PsgCountNum + 1);
Console.WriteLine($"Cost per Occupant: {Currency,33}{CCP:00.00}");
double CPM = Fuelcost / DistanceNum;
Console.WriteLine($"Cost per Mile: {Currency,37}{CPM:00.00}");
double CPH = totaltime / Fuelcost;
Console.WriteLine($"Cost per every hour Driven: {Currency,24}{CPH:00.00}");
Console.WriteLine();
double avgsonglength = 3.5;
Console.WriteLine($"Average song Length in minutes: {avgsonglength,25:0.0}");
double totaltimemin = totaltime * 60;
int songsneeded = (int)(totaltimemin / avgsonglength) + 1;
Console.WriteLine($"Number of songs needed: {songsneeded,33}");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("Press any button + Enter to close");
Console.ReadLine();